source :rubygems

gem 'dm-core'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'dm-aggregates'
gem 'dm-timestamps'
gem 'json'
gem 'rack'
gem 'sinatra'
#gem 'sinatra_more'